package com.aventura.cookbook;

import java.awt.Color;

import com.aventura.math.transform.Rotation;
import com.aventura.math.transform.Translation;
import com.aventura.math.vector.Vector3;
import com.aventura.model.texture.Texture;
import com.aventura.model.world.Element;
import com.aventura.model.world.shape.ConeFrustum;
import com.aventura.model.world.shape.Disc;

/**
 * ------------------------------------------------------------------------------
 * MIT License
 *
 * Copyright (c) 2016-2026 Olivier BARRY
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 * ------------------------------------------------------------------------------
 *
 * Cookbook recipe 3 (see docs/GEOMETRY_COOKBOOK.md): enriching an existing shape by inheritance.
 *
 * ConeFrustum is only the lateral surface of a truncated cone (open at both ends). This subclass
 * closes it with 2 Discs attached as sub-Elements, each one placed by its own transformation:
 *
 *     ClosedConeFrustum (the lateral surface: inherited geometry, untouched)
 *       +-- top    Disc (radius of the top circle), translated up to the top circle
 *       +-- bottom Disc (radius of the base),       turned upside down, then translated down
 *
 * The lateral surface keeps being generated by ConeFrustum: this class adds sub-Elements and
 * extends the Shape API (top/bottom color and texture), nothing else.
 *
 * Local frame inherited from ConeFrustum: the axis is Z, the base circle (radius ray) is at
 * z = -coneHeight/2 and the (virtual) apex of the full cone at z = +coneHeight/2; the frustum stops
 * at z = frustumHeight - coneHeight/2, where the radius is ray * (coneHeight - frustumHeight) / coneHeight.
 *
 * @author Olivier BARRY
 * @since 2026
 */
public class ClosedConeFrustum extends ConeFrustum {

	protected static final String CLOSED_CONE_FRUSTUM_DEFAULT_NAME = "closed cone frustum";

	// ConeFrustum's own fields (ray, cone_height, frustum_height, half_seg) are package-private: a
	// subclass in another package cannot read them, so it keeps its own copy of the parameters.
	protected final float coneHeight, frustumHeight, baseRay;
	protected final int halfSeg;

	protected Disc top, bottom;

	/**
	 * @param coneHeight    height of the full (untruncated) cone
	 * @param frustumHeight height of the frustum, 0 < frustumHeight < coneHeight
	 * @param ray           radius of the base
	 * @param halfSeg       half the number of segments of the circles (same for the discs, so that
	 *                      their edges match the lateral surface exactly: no crack)
	 */
	public ClosedConeFrustum(float coneHeight, float frustumHeight, float ray, int halfSeg) {
		this(coneHeight, frustumHeight, ray, halfSeg, null);
	}

	/** Same, with a texture on the lateral surface (see setTopTexture()/setBottomTexture() for the discs). */
	public ClosedConeFrustum(float coneHeight, float frustumHeight, float ray, int halfSeg, Texture tex) {
		super(coneHeight, frustumHeight, ray, halfSeg, tex); // 1. the parent constructor stores ITS parameters
		if (frustumHeight <= 0 || frustumHeight >= coneHeight || ray <= 0 || halfSeg < 2) {
			throw new IllegalArgumentException("ClosedConeFrustum: 0 < frustumHeight < coneHeight, ray > 0 and halfSeg >= 2 required");
		}
		this.coneHeight = coneHeight;
		this.frustumHeight = frustumHeight;
		this.baseRay = ray;
		this.halfSeg = halfSeg;
		this.name = CLOSED_CONE_FRUSTUM_DEFAULT_NAME; // (the parent constructor set its own default name)
		this.isClosed = true; // 2. with its caps, the shape is now watertight: back-face culling allowed
		createSubElements();  // 3. sub-Elements are created in the constructor, before build()
	}

	/**
	 * The caps. A Disc lies in its local XY plane, centered on its origin, facing +Z (its triangles are
	 * wound counter-clockwise seen from +Z). The top one already faces outwards: a translation is
	 * enough. The bottom one must face -Z: it is first turned upside down (half-turn around X), then
	 * translated -- M = T . R, the rotation being applied first, around the Disc's own center.
	 */
	protected void createSubElements() {
		float zBottom = -coneHeight / 2;
		float zTop = frustumHeight - coneHeight / 2;
		float topRay = baseRay * (coneHeight - frustumHeight) / coneHeight;

		top = new Disc(topRay, halfSeg);
		top.setTransformation(new Translation(Vector3.zAxis(), zTop));
		addElement(top);

		bottom = new Disc(baseRay, halfSeg);
		bottom.setTransformation(new Rotation((float) Math.PI, Vector3.xAxis()));  // first: upside down
		bottom.combineTransformation(new Translation(Vector3.zAxis(), zBottom));   // then: moved down
		addElement(bottom);
	}

	// generateVertices(), generateTriangles() and calculateNormals() are NOT overridden: the inherited
	// ones generate the lateral surface, and build() then builds the sub-Elements (Element.subBuild()).
	// An override that adds geometry to THIS Element would call super.generateVertices() first.

	/** Volume of the frustum (to check the winding with ElementContractChecker.signedVolume()). */
	public float getVolume() {
		float topRay = baseRay * (coneHeight - frustumHeight) / coneHeight;
		return (float) (Math.PI * frustumHeight / 3 * (baseRay * baseRay + baseRay * topRay + topRay * topRay));
	}

	// Shape API: ConeFrustum (via Element) returns null for these, meaning "not supported". The caps
	// make them meaningful: delegate to the Disc, and return this.

	@Override
	public Element setTopColor(Color c) {
		top.setColor(c);
		return this;
	}

	@Override
	public Element setBottomColor(Color c) {
		bottom.setColor(c);
		return this;
	}

	@Override
	public Element setTopTexture(Texture tex) {
		top.setFrontTexture(tex); // must be called before build(), like any texture setter
		return this;
	}

	@Override
	public Element setBottomTexture(Texture tex) {
		bottom.setFrontTexture(tex);
		return this;
	}
}
